import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Script from "next/script";
import styles from "@/styles/Home.module.css";
import Link from "next/Link"
import Dummy from "../../components/Dummy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src=""></script> */}
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}
      <div className={styles.main}>
      <style jsx>
          {
            
              `.mySpan{
                color:red
              }

              .blogContainer{
                margin-top:20px;
              }

              .pb{
                margin:20px;
                margin-left:0px;
              }

              .header{
                margin-top:10px;
              }

              .img{
                border-radius:5px;
                border: 2px solid red;
              }
              
              `
            
          }
           
        </style>
        {/* <Dummy/> */}
      
        
        <h1 className={styles.mtb}> <span className="mySpan">Code Hunter</span> </h1>
        <p className={styles.mtb}>Start blogging with us...</p>

        <Image className="img" src="/blog.avif" width={350} height={200}></Image>

        <div className="blog blogContainer">
          <h1 className="pb">Popular Blogs</h1>
          <div className="header">
            <h2>How to learn Next js</h2>
            <p>we can learn next js through many open source materials</p>
          </div>

          <div className="header">
            <h2>How to learn  python</h2>
            <p>we can learn python through many open source materials</p>
          </div>

          <div className="header">
            <h2>How to learn java</h2>
            <p>we can learn java through many open source materials</p>
          </div>
        </div>

        
      </div>
    </>
  );
}
